[build]
  command = "quarto render"
  publish = "public"  # or the directory where HTML output is stored

[build.environment]
  QUARTO_VERSION = "1.4.552"  # Replace with your quarto version

[[plugins]]
  package = "netlify-plugin-quarto"

